### ISSUE TITLE
Stats Nag incorrect count

### ISSUE THREAD

**Issue by msmaldi** [niklasf/rust-pgn-reader#11]
Consider game:

[Seven "Tags..."]
1.f3 e5 2.g4?? Qh4#

the result is Stats { games: 1, headers: 1, sans: 4, nags: 2, comments: 0, variations: 0, outcomes: 0 }
the expected is Stats { games: 1, headers: 1, sans: 4, nags: **1**, comments: 0, variations: 0, outcomes: 0 }

2 nags is found, cause have 2 characters '?', but it is a single annotation equals $4 very poor move (traditional "??").
Another annotation have same issues: !!, ??, !? and ?!

**Comment by niklasf** [comment]
Thanks for reporting. Will publish a release with this fix (and some dependency updates) shortly.
